# Generated by Django 5.1.4 on 2025-01-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_cliente_imovel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='ano_construcao',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='banheiros',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='estado',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='garagem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='metro_area_construida',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='metro_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='propietario',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='relacao',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrocliente',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cadastrocliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastrocliente',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cnpj',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cpf',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
