# Generated by Django 5.1.4 on 2025-01-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_caracteristicaimovel_imovel_ano_construcao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piscina', models.BooleanField(default=False)),
                ('churrasqueira', models.BooleanField(default=False)),
                ('jardim', models.BooleanField(default=False)),
                ('varanda', models.BooleanField(default=False)),
                ('armario', models.BooleanField(default=False)),
                ('elevador', models.BooleanField(default=False)),
                ('outros', models.CharField(max_length=50)),
                ('descricao_imovel', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.cadastrocliente')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escritura', models.BooleanField(default=False)),
                ('troca_menor', models.BooleanField(default=False)),
                ('troca_maior', models.BooleanField(default=False)),
                ('divida', models.BooleanField(default=False)),
                ('detalhes', models.CharField(blank=True, max_length=100, null=True)),
                ('rg_img', models.ImageField(upload_to='docs')),
                ('cpf_img', models.ImageField(upload_to='docs')),
                ('comprovante_residencia', models.ImageField(upload_to='docs')),
                ('rosto', models.ImageField(upload_to='docs')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.cadastrocliente')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(null=True, upload_to='fotos')),
                ('descricao_imagem', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CaracteristicaImovel',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentacao',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='documentacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='documentacao',
            field=models.ManyToManyField(to='imoveis.documentacao'),
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='imagens',
            field=models.ManyToManyField(to='imoveis.imagens'),
        ),
    ]
