# Generated by Django 5.1.4 on 2025-01-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_cadastrocliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
