# Generated by Django 5.1.4 on 2025-01-05 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_cadastrocliente_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='cpf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cpf'),
        ),
    ]
