# Generated by Django 5.1.4 on 2025-01-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_alter_cadastrocliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='cpf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imoveis.cpf'),
        ),
        migrations.AlterField(
            model_name='cpf',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
