# Generated by Django 5.1.4 on 2025-01-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_alter_cadastrocliente_cpf_alter_cpf_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
