# Generated by Django 5.1.4 on 2025-01-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_alter_cadastrocliente_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
